# Spring
spring:
  application.name: Celebrity-Strike

#Datasource
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/${CELEBRITY_STRIKE_DB}
    username: ${CELEBRITY_STRIKE_USER}
    password: ${CELEBRITY_STRIKE_PASSWORD}

#Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.sql

# Server
server:
  port: 18080

# Telegram
telegram:
  bot:
    token: ${BOT_TOKEN}
    frontend-url: https://elenasoshina.github.io
