name: celebrity-strike
services:
  celebrity-strike-db:
    image: postgres:17
    container_name: celebrity-strike-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${CELEBRITY_STRIKE_DB}
      POSTGRES_USER: ${CELEBRITY_STRIKE_USER}
      POSTGRES_PASSWORD: ${CELEBRITY_STRIKE_PASSWORD}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - ../nginx/vhost.d:/etc/nginx/vhost.d:ro
      - html:/usr/share/nginx/html

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - ACME_CA_URI=https://acme-v02.api.letsencrypt.org/directory
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - ../nginx/vhost.d:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html

  celebrity-strike-backend:
    image: celebrity-strike:latest
    container_name: celebrity-strike
    restart: always
    environment:
      - VIRTUAL_PORT=18080
      - VIRTUAL_HOST=celebrity-strike.duckdns.org
      - LETSENCRYPT_HOST=celebrity-strike.duckdns.org
      - LETSENCRYPT_EMAIL=gotziev@gmail.com
      - BOT_TOKEN=${BOT_TOKEN}
    expose:
      - "18080"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  certs:
  vhost:
  html:
