name: celebrity-strike-app
services:
  celebrity-strike-backend:
    image: celebrity-strike:latest
    container_name: celebrity-strike
    restart: always
    environment:
      - DATABASE_HOST=celebrity-strike-db
      - VIRTUAL_PORT=18080
      - VIRTUAL_HOST=celebrity-strike.duckdns.org
      - LETSENCRYPT_HOST=celebrity-strike.duckdns.org
      - LETSENCRYPT_EMAIL=gotziev@gmail.com
      - BOT_TOKEN=${BOT_TOKEN}
      - CELEBRITY_STRIKE_DB=${CELEBRITY_STRIKE_DB}
      - CELEBRITY_STRIKE_USER=${CELEBRITY_STRIKE_USER}
      - CELEBRITY_STRIKE_PASSWORD=${CELEBRITY_STRIKE_PASSWORD}
      - DATABASE_HOST=celebrity-strike-db
    expose:
      - "18080"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      celebrity_network:
        aliases:
          - celebrity-strike
networks:
  celebrity_network:
    external: true