--liquibase formatted sql

-- changeset vnsemkin:1
CREATE TABLE games
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    title       VARCHAR(255),
    description TEXT,
    instruction TEXT,
    PRIMARY KEY (id)
);

-- changeset vnsemkin:2
CREATE TABLE images
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    image_url VARCHAR(255) NOT NULL,
    game_id   BIGINT       NOT NULL,
    PRIMARY KEY (id)
);

-- changeset vnsemkin:3
CREATE TABLE game_items
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(255) NOT NULL,
    type    VARCHAR(255) NOT NULL,
    region  VARCHAR(255) NOT NULL,
    details VARCHAR(255),
    price   INTEGER      NOT NULL,
    game_id BIGINT       NOT NULL,
    PRIMARY KEY (id)
);

-- changeset vnsemkin:4
ALTER TABLE images
    ADD CONSTRAINT fk_images_game
        FOREIGN KEY (game_id) REFERENCES games (id);

-- changeset vnsemkin:5
ALTER TABLE game_items
    ADD CONSTRAINT fk_game_items_game
        FOREIGN KEY (game_id) REFERENCES games (id);