name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '23'

      - name: Build with Gradle
        run: gradle build -x test

      - name: Build Docker image
        run: docker build -t celebrity-strike:latest .

      - name: Save Docker image as tar file
        run: docker save celebrity-strike:latest > celebrity-strike.tar

      - name: Check tar file size
        run: ls -lh celebrity-strike.tar

      - name: Move tar file into folder
        run: |
          mkdir -p deploy
          mv celebrity-strike.tar deploy/

      # New step: Clear remote /tmp/deploy folder before copy
      - name: Clear remote /tmp/deploy folder
        uses: appleboy/ssh-action@master
        with:
          host: 192.248.160.151
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          script: |
            rm -rf /tmp/deploy
            mkdir -p /tmp/deploy
            mkdir -p /docker

      - name: Copy Docker image to remote server
        uses: appleboy/scp-action@master
        with:
          host: 192.248.160.151
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          source: "deploy/celebrity-strike.tar"
          target: "/tmp/deploy/"
          timeout: 300s
          proxy_timeout: 180s
          strip_components: 1

      # New step: Copy vhost.d configuration to remote server
      - name: Copy vhost.d configuration to remote server
        uses: appleboy/scp-action@master
        with:
          host: 192.248.160.151
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          source: "nginx/vhost.d/"
          target: "/docker/vhost.d/"
          timeout: 300s
          proxy_timeout: 180s
          strip_components: 1

      # New step: Copy docker-compose-nginx.yml to remote server
      - name: Copy docker-compose-nginx.yml to remote server
        uses: appleboy/scp-action@master
        with:
          host: 192.248.160.151
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          source: "docker/*"
          target: "/docker/"
          timeout: 300s
          proxy_timeout: 180s
          strip_components: 1

      - name: Deploy Docker container on remote server
        uses: appleboy/ssh-action@master
        with:
          host: 192.248.160.151
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          script: |
            docker network create celebrity_network
            docker load -i /tmp/deploy/celebrity-strike.tar
            docker compose -f /docker/docker-compose-postgres.yml up -d --no-recreate
            docker compose -f /docker/docker-compose-app.yml up -d
            docker compose -f /docker/docker-compose-nginx.yml up -d --no-recreate
            echo "Pruning unused Docker images..."
            docker image prune -af
            rm -f /tmp/deploy/celebrity-strike.tar